### ISSUE TITLE
Remove games that do not work

### ISSUE THREAD

**Issue by gen1e** [Women-in-Computing-at-RIT/RaspberryPiArcadeCabinet#4]
There are some games that don't work. @ldidonato do you know the ones that don't work that you are aware of.

Probably need to take off Zork if it is still installed because that requires a keyboard.

**Comment by aviggiano836** [comment]
All games were removed and will need to be re-added

**Comment by gen1e** [comment]
I'm pretty sure Kevin took care of this, we should be good.
